name: DevOps End-to-End Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        id: tf
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -replace="aws_instance.app_server"
          echo "INSTANCE_IP=$(terraform output -raw target_server_public_ip)" >> $GITHUB_ENV
          echo "New Instance IP is: $INSTANCE_IP"

      - name: Set up SSH Private Key
        run: |
          echo "INSTANCE_IP is: ${{ env.INSTANCE_IP }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_NEW }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh
          if [ -n "${{ env.INSTANCE_IP }}" ]; then
            ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts
          else
            echo "WARNING: INSTANCE_IP is empty!"
          fi

      - name: Run Ansible Playbook Configuration
        run: |
          cd ansible
          echo "${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" > inventory.ini
          echo "=== Inventory content ==="
          cat inventory.ini
          ansible-playbook -i inventory.ini playbook.yml
